apiVersion: v1
kind: Service
metadata:
  name: ibm-Cloud-tic-tac-toe
spec:
  selector:
    app: ibm-Cloud-tic-tac-toe
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-Cloud-tic-tac-toe
  labels:
    app: ibm-Cloud-tic-tac-toe
spec:
  selector:
    matchLabels:
      app: ibm-Cloud-tic-tac-toe
  replicas: 1
  template:
    metadata:
      labels:
        app: ibm-Cloud-tic-tac-toe
    spec:
      containers:
      - name: ibm-Cloud-tic-tac-toe
        image: quay.io/codait/ibm-Cloud-tic-tac-toe:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"